name: diabetes-mlproject
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas==2.2.2
      - numpy==1.26.4
      - scikit-learn==1.5.2
      - joblib==1.4.2
